on: [ push ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: cargo fmt
      run: cargo fmt --all -- --check
        
    - name: cargo build
      run: cargo build

    - name: cargo test
      run: cargo test

  build_macos:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: cargo fmt
      run: cargo fmt --all -- --check
        
    - name: cargo build
      run: cargo build

    - name: cargo test
      run: cargo test

  # build_windows:
  #   runs-on: windows-latest
  #   steps:
  #   - name: checkout
  #     uses: actions/checkout@v3

  #   - name: setup msbuild
  #     uses: microsoft/setup-msbuild@v1.1.3

  #   - name: msbuild
  #     run: |
  #       msbuild windows\ZeroTierOne.sln /m /p:Configuration=Release  /property:Platform=x64 /t:ZeroTierOne:Rebuild
